### ISSUE TITLE
Swift 4 NSForegroundColorAttributeName compatibility

### ISSUE THREAD

**Issue by nasznjoka** [originaluser2/Pie-Chart-View#2]
On swift 4 NSForegroundColorAttributeName appears to be not resolvable 
also this has errors 
var renderRect = CGRect(origin: .zero, size: textToRender.size(attributes: textAttributes))

**Comment by nasznjoka** [comment]
Seems all over places. can you convert this class to be swift 4 compatible?

**Comment by hamishknight** [comment]
Thanks, should be resolved by 7da204e2b144851ab041ead32247eb53b133c449!

**Comment by nasznjoka** [comment]
private lazy var textAttributes: [NSAttributedString.Key: Any] = [
    .paragraphStyle: self.paragraphStyle, .font: self.segmentLabelFont
  ] still got errors on this one line

**Comment by hamishknight** [comment]
What errors do you get? Compiles with Swift 4.2 beta in Xcode 10 beta 6.

**Comment by nasznjoka** [comment]
<img width="1680" alt="screen shot 2018-08-19 at 19 58 26" src="https://user-images.githubusercontent.com/3130364/44311117-44fe6e80-a3ea-11e8-98e6-280a8692236e.png">
check the screen short, am on swift 4.1

**Comment by hamishknight** [comment]
Ah, I see – should be fixed by 50b4671a381fcf7c288c9e18f74389f50063f181.

**Comment by nasznjoka** [comment]
Ok thanks. It is fixed and it's compatible now
Regards

**Comment by nasznjoka** [comment]
OK so when I run the project executes well, but when I open the view with the graph the app crashes on init, please check the screenshot. I'm using the graph on a view and referencing it using IBOutlet.
<img width="1680" alt="screen shot 2018-08-23 at 09 04 02" src="https://user-images.githubusercontent.com/3130364/44507605-d48a7280-a6b3-11e8-8a16-5b7139a88971.png">

**Comment by hamishknight** [comment]
Yeah I didn't make the classes compatible with Interface Builder – just added that in ee5708897c558a9c1bdc50b76f98c24ffaaf6c21.

**Comment by nasznjoka** [comment]
Thanks it's alright now.
